apiVersion: v1
kind: ReplicationController
metadata:
  name: es
  labels:
    name: es
    app: foodtruck
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: es
        app: foodtruck
    spec:
       containers:
         - name: es1
           image: elasticsearch:2.3
           ports:
             - containerPort: 9200
