apiVersion: v1
kind: ReplicationController
metadata:
   name: ft
   labels:
     name: ft
     app: foodtruck
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: ft
        app: foodtruck
    spec:
       containers:
         - name: ft1
           image: prakhar1989/foodtrucks-web
           ports:
             - containerPort: 5000
