apiVersion: v1
kind: Service
metadata:
  name: ft
  labels:
    name: ft
    app: foodtruck
spec:
  selector:
    name: ft
  type: NodePort
  ports:
   - port: 80
     targetPort: 5000
     nodePort: 6080
     protocol: TCP
